In [1]:
import numpy as np

compressed_imagenet = np.load("reduced_images.npy")

In [2]:
# Set print options to display floats with two decimal places
np.set_printoptions(precision=2, suppress=True)

# Compute correlation matrix for all 10 features
correlation_matrix = np.corrcoef(compressed_imagenet, rowvar=False)
print(correlation_matrix)

[[ 1.    0.36  0.83  0.28  0.49 -0.38]
 [ 0.36  1.    0.38 -0.04  0.16 -0.03]
 [ 0.83  0.38  1.    0.43  0.88  0.02]
 [ 0.28 -0.04  0.43  1.    0.33  0.69]
 [ 0.49  0.16  0.88  0.33  1.    0.21]
 [-0.38 -0.03  0.02  0.69  0.21  1.  ]]


In [3]:
# Compute variances of features
feature_variances = np.var(compressed_imagenet, axis=0)
print(feature_variances)

[2.35 0.12 2.08 0.06 0.79 0.35]
